In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3,4]) #создаем массив из стандартного массива 
print(a)

[1 2 3 4]


In [4]:
a = np.zeros(4) #создаем одномерный массив из нулей
print(a)

[0. 0. 0. 0.]


In [14]:
a = np.ones((4, 2)) #создаем матрицу формы 4x2 из единиц
print(a)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [8]:
a = np.arange(5) #создаем список из чисел от 0 до 4
print(a)
print(a.shape) #форма
print(a.dtype) #тип данных внутри

[0 1 2 3 4]
(5,)
int64


In [11]:
a = np.arange(20)
print(a[5]) #конкретный элемент
print(a[2:12]) #срез

5
[ 2  3  4  5  6  7  8  9 10 11]


In [18]:
a = np.arange(10)
b = np.arange(5, 15)
print(a, b)
print(a + b) #складываем векторы

[0 1 2 3 4 5 6 7 8 9] [ 5  6  7  8  9 10 11 12 13 14]
[ 5  7  9 11 13 15 17 19 21 23]


In [20]:
a = np.arange(10, 31)
print(a.mean()) #среднее значение. (10 + 30)/ 2 = 20

20.0
